'use strict';
// Builds worker/generated/tulip_core.mjs: ONE self-contained ES module that holds
//   * the approved runtime knowledge (system prompt + rules + facts, hash-verified by src/knowledge.js against the build manifest),
//   * config/model.json, config/guards.json, and the local reasoning-variant choice,
//   * the unchanged shared source modules (guards, sentences, observations, ledger, session core, adapter helpers).
// Nothing else from the project is read: original inputs, source reports, evaluations, checkpoints, logs and admin notes are never opened.
// Run: node scripts/build_worker.js          (writes the file; it is git-ignored because it contains YOUR knowledge)
//      node scripts/build_worker.js --check  (fails if the generated file is stale)
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'worker', 'generated', 'tulip_core.mjs');

// The complete list of project files that may enter the Worker bundle (besides the three runtime knowledge files read by loadRuntime).
const SOURCE_MODULES = [
  'src/guards.js', 'src/sentences.js', 'src/observations.js', 'src/ledger.js', 'src/session_core.js',
  'src/adapters/errors.js', 'src/adapters/parse.js',
];
const JSON_MODULES = ['config/guards.json', 'config/model.json'];

const posix = path.posix;
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8').replace(/\r\n/g, '\n');

function rewriteRequires(rel, src) {
  return src.replace(/require\(\s*'([^']+)'\s*\)/g, (_m, spec) => {
    if (spec.startsWith('.')) {
      let id = posix.normalize(posix.join(posix.dirname(rel), spec));
      if (!id.endsWith('.js') && !id.endsWith('.json')) id += '.js';
      if (!SOURCE_MODULES.includes(id) && !JSON_MODULES.includes(id)) throw new Error(rel + ' requires ' + id + ', which is not on the Worker bundle list.');
      return '__req(' + JSON.stringify(id) + ')';
    }
    return '__req(' + JSON.stringify('node:' + spec.replace(/^node:/, '')) + ')'; // Node built-ins: unavailable in the Worker (only reachable from code paths the Worker never runs)
  });
}

// opts.runtimeDir: where the built rules.md / facts.md / manifest.json are (default knowledge_base/runtime); opts.outFile: output path.
function generate(opts = {}) {
  const { loadRuntime } = require('../src/knowledge.js');
  const G = require('../src/guards.js');
  const knowledge = loadRuntime(G.CFG.runtime_flags, { runtimeDir: opts.runtimeDir });   // throws if rules.md / facts.md do not match the build manifest
  const choices = fs.existsSync(path.join(ROOT, 'config', 'local_choices.json')) ? JSON.parse(read('config/local_choices.json')) : {}; // optional, written by scripts/probe_reasoning.js
  const modelCfg = JSON.parse(read('config/model.json'));
  const systemSha = crypto.createHash('sha256').update(knowledge.system, 'utf8').digest('hex');

  const defs = [];
  for (const rel of SOURCE_MODULES) {
    const body = rewriteRequires(rel, read(rel));
    defs.push('  ' + JSON.stringify(rel) + ': function (module, exports, __req, __dirname) {\n' + body + '\n  },');
  }
  for (const rel of JSON_MODULES) {
    defs.push('  ' + JSON.stringify(rel) + ': function (module) { module.exports = ' + JSON.stringify(JSON.parse(read(rel))) + '; },');
  }

  const info = {
    prompt_version: knowledge.info.prompt_version,
    knowledge_base_version: knowledge.info.knowledge_base_version,
    system_sha256: systemSha,
    system_chars: knowledge.system.length,
    model: modelCfg.model,
    reasoning_variant: choices.reasoning_variant || 'no_think_suffix', // default for Qwen3 models; scripts/probe_reasoning.js may record another choice
    modules: [...SOURCE_MODULES, ...JSON_MODULES],
  };

  return [
    '// GENERATED by scripts/build_worker.js. Do not edit; run `node scripts/build_worker.js` instead.',
    '// Contains only the approved runtime knowledge and the shared Tulip modules. It runs server-side in the Worker and is never served to browsers.',
    'const defs = {',
    defs.join('\n'),
    '};',
    'const cache = {};',
    'function load(id) {',
    '  if (cache[id]) return cache[id].exports;',
    "  if (id.startsWith('node:')) throw new Error('Node module ' + id + ' is not available in the Worker.');",
    "  const def = defs[id]; if (!def) throw new Error('Unknown bundled module ' + id);",
    '  const m = { exports: {} }; cache[id] = m; def(m, m.exports, load, "/"); return m.exports;',
    '}',
    "const G = load('src/guards.js');",
    "const ledgerMod = load('src/ledger.js');",
    "const parse = load('src/adapters/parse.js');",
    'export const guards = G;',
    "export const TulipSession = load('src/session_core.js').TulipSession;",
    'export const Ledger = ledgerMod.Ledger;',
    'export const BudgetError = ledgerMod.BudgetError;',
    "export const ModelError = load('src/adapters/errors.js').ModelError;",
    'export const cleanContent = parse.cleanContent;',
    'export const extract = parse.extract;',
    'export const MODEL_CFG = load("config/model.json");',
    'export const REASONING_VARIANT = ' + JSON.stringify(info.reasoning_variant) + ';',
    'export const KNOWLEDGE = ' + JSON.stringify({ system: knowledge.system, facts: knowledge.facts, info: knowledge.info }) + ';',
    'export const BUILD_INFO = ' + JSON.stringify(info) + ';',
    '',
  ].join('\n');
}

function write(opts = {}) {
  const out = generate(opts);
  const file = opts.outFile || OUT;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, out);
  console.log('wrote ' + path.relative(ROOT, file).split(path.sep).join('/') + ' (' + out.length + ' chars)');
}

if (require.main === module) {
  if (process.argv.includes('--check')) {
    const out = generate();
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (cur !== out) { console.error('worker/generated/tulip_core.mjs is stale. Run: npm run build:worker'); process.exit(1); }
    console.log('worker bundle is up to date');
  } else write();
}
module.exports = { generate, write, SOURCE_MODULES, JSON_MODULES, OUT };
